version: "3.9"
services:
  #
  # `tusd` offers resumable uploads.
  # Files are first uploaded into `upload-dir` and
  # then moved to Besace root folder in hooks scripts.
  #
  tusd:
    restart: unless-stopped
    image: tusproject/tusd:v2
    environment:
      - BESACE_ROOT_FOLDER=/srv/tusd-data/besace
    volumes:
      - ./hooks:/srv/tusd-hooks:ro
      - ./volumes/tusd-data:/srv/tusd-data/incoming:rw
      - ./volumes/root-folder:/srv/tusd-data/besace:rw
    command: -hooks-dir /srv/tusd-hooks -base-path /tusd/ -upload-dir /srv/tusd-data/incoming -behind-proxy -hooks-enabled-events "pre-create,post-finish" -max-size 1000000000
    expose:
      - "8080"
    ports:
      - 127.0.0.1:9001:8080

  #
  # `api` creates Besace folders, returns files lists,
  # generates downloadable archives, etc.
  #
  api:
    restart: unless-stopped
    build:
      context: ./api/
      args:
        # Same as tusd to share writable folder
        userid: 1000
        groupid: 1000
    image: api
    # Let the init system handle signals for us.
    # among other things this helps shutdown be fast
    init: true
    environment:
      - ROOT_URL_PATH=/api
      - BESACE_ROOT_FOLDER=/mnt/uploads
      - BESACE_RETENTION_DAYS=7
      - BESACE_CREATE_SECRETS=${BESACE_CREATE_SECRETS:-s2cr2t,s3cr3t}
    volumes:
      - ./api:/app:rw
      - ./volumes/root-folder:/mnt/uploads:rw
    expose:
      - "8000"
    ports:
      - 127.0.0.1:9002:8000

  #
  # `thumbnailer` monitors a folder for input files and
  # creates thumbnail files in another.
  #
  thumbnailer:
    restart: unless-stopped
    build:
      context: ./thumbnailer/
    image: thumbnailer
    init: true
    environment:
      - BESACE_ROOT_FOLDER=/mnt/uploads
      - BESACE_THUMBNAILS_FOLDER=/mnt/thumbnails
    volumes:
      - ./thumbnailer:/app:rw
      - ./volumes/root-folder:/mnt/uploads:rw
      - ./volumes/thumbnails:/mnt/thumbnails:rw

  #
  # `web` serves the static files for the Web UI, and
  # is the reverse proxy for `api` and `tusd`.
  #
  web:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:ro
      - ./volumes/thumbnails:/var/www/thumbnails:ro
    ports:
      - 127.0.0.1:${BESACE_HTTP_PORT:-8080}:80
