#!/bin/sh
eventPayload=$(cat /dev/stdin | jq .)
folder_id=$(echo $eventPayload | jq -r .Event.Upload.MetaData.folderId)
source=$(echo $eventPayload | jq -r .Event.Upload.Storage.Path)

echo "Receiving ${source}" >&2

if [[ "${folder_id}" == *\/* ]]; then
    echo "Invalid folder ${folder_id}" >&2
    echo "{\"detail\": \"Invalid folder ${folder_id}\"}"
    exit 1
fi

echo "Checking folder ${BESACE_ROOT_FOLDER}/${folder_id}/" >&2
if [ ! -d "${BESACE_ROOT_FOLDER}/${folder_id}" ]; then
    echo "Unknown folder ${folder_id}" >&2
    echo "Deleting ${source}" >&2
    rm -f "${source}*"
    echo "{\"detail\": \"Unknown folder ${folder_id}\"}"
    exit 1
fi
