[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Mathieu Leplatre <mathieu@leplat.re>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111"
uvicorn = {extras = ["standard"], version = "^0.29"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
